server:
  port: {{SERVER_PORT}}
  error:
    path: "/error"

spring:
  application:
    name: cro-api
  #  data:
  #    mongodb:
  #      uri: mongodb://cro_user:123456@127.0.0.1:27017/cro
  datasource:
    url: jdbc:mysql://{{DB_HOST}}:{{DB_PORT}}/{{DB_DATABASE}}?serverTimezone=UTC
    username: {{DB_USERNAME}}
    password: {{DB_PASSWORD}}
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: utf-8
        useSSL: false
  flyway:
    locations: classpath:db/migrations

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cro:
  open-ai-token: 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
  token-cache-time: 28800 # 缓存8小时
  upload-file-path: {{UPLOAD_FILE_PATH}}
  ai-url: http://101.34.251.26:8081
