server:
  port: 8080
  error:
    path: "/error"

spring:
  application:
    name: cro-api
  data:
    mongodb:
      uri: mongodb://cro_user:123456@127.0.0.1:27017/cro

cro:
  open-ai-token: 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

