version: '3.1'

services:
  mongo:
    image: mongo:3.6.23
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cro
      MONGO_INITDB_ROOT_PASSWORD: cro_password
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://cro:cro_password@mongo:27017/